const ACTION_TYPES = {
  API_PENDING: 'FETCH_ALL_BREEDS_SERVICE_PENDING',
  API_SUCCESS: 'FETCH_ALL_BREEDS_SERVICE_SUCCESS',
  API_ERROR: 'FETCH_ALL_BREEDS_SERVICE_ERROR',
};
export default ACTION_TYPES;
